import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import EmptyTableRows from '../components/EmptyTableRows';
import { latestMetric, queryMetric, apScoped, type MetricPoint } from '../api/metrics';
import BarList, { type BarListItem } from '../components/viz/BarList';
import LineChart, { type LineSeries } from '../components/viz/LineChart';
import type { ReactNode } from 'react';
import { useTimeRange } from '../components/TimeRange';
import s from './AccessPointsPage.module.css';

type AP = { name: string; clients: number; two: number; five: number; cpu: number; memory: number; rssi: string };
const initialAps: AP[] = [];

function Chart({ title, subtitle, format, yMax, area = false, series = [] }: { title: string; subtitle?: string; bases?: number[]; format?: (v: number) => string; yMax?: number; area?: boolean; series?: LineSeries[] }) {
  return <LineChart title={title} subtitle={subtitle} series={series} height={164} yFormat={format} yMax={yMax} area={area} />;
}
function Panel({ title, children }: { title: string; children: ReactNode }) { return <section className={s.listPanel}><h2>{title}</h2>{children}</section>; }

export default function AccessPointsPage() {
  const tr = useTimeRange();
 const [aps, setAps] = useState<AP[]>(initialAps); const [count, setCount] = useState(0); const [clients, setClients] = useState(0); const [two, setTwo] = useState(0); const [five, setFive] = useState(0);
 useEffect(() => { void queryMetric('unpoller_device_info').then(rows => { const live = rows.filter(r => r.labels?.type === 'uap' || (r.labels?.type === 'udm' && /^UDMA/.test(r.labels?.model ?? ''))).map(r => ({ name: r.labels?.name ?? 'Unknown', clients: Number.NaN, two: Number.NaN, five: Number.NaN, cpu: Number.NaN, memory: Number.NaN, rssi: '—' })); setAps(live); setCount(live.length); }).catch(() => undefined); }, [tr.earliest, tr.range, tr.refreshKey]);
  useEffect(() => { void Promise.all([latestMetric(`count(${apScoped('unpoller_device_uptime_seconds')})`,7), latestMetric(`sum(${apScoped('unpoller_device_stations')})`,28), latestMetric('sum(unpoller_device_radio_stations{radio="ng"})',14), latestMetric('sum(unpoller_device_radio_stations{radio="na"})',14)]).then(([a,c,n,f]) => { setCount(a);setClients(c);setTwo(n);setFive(f); }); }, [tr.earliest, tr.range, tr.refreshKey]);
  const [chartSeries, setChartSeries] = useState<Record<string, LineSeries[]>>({});
  const [channelItems, setChannelItems] = useState<BarListItem[]>([]);
  const [vendorItems, setVendorItems] = useState<BarListItem[]>([]);
  useEffect(() => { const specs: Record<string, string> = { clients: `sum by (name) (${apScoped('unpoller_device_stations')})`, signal: 'avg by (ap_name) (unpoller_client_rssi_db)', tx: 'sum by (name) (rate(unpoller_device_vap_transmit_bytes_total[5m]))', rx: 'sum by (name) (rate(unpoller_device_vap_receive_bytes_total[5m]))', util24: '100 * avg by (name) (unpoller_device_radio_channel_utilization_total_ratio{band="2.4"})', util5: '100 * avg by (name) (unpoller_device_radio_channel_utilization_total_ratio{band="5"})', cpu: `100 * max by (name) (${apScoped('unpoller_device_cpu_utilization_ratio')})`, memory: `100 * max by (name) (${apScoped('unpoller_device_memory_utilization_ratio')})` }; const colors = ['#347fce','#238b3c','#d36b96','#d69d2d','#3a9d84']; void Promise.all(Object.entries(specs).map(async ([key, query]) => [key, await queryMetric(query, tr.step, tr.earliest)] as const)).then(results => { const next: Record<string, LineSeries[]> = {}; for (const [key, rows] of results) { const grouped = new Map<string, MetricPoint[]>(); rows.forEach(row => { const name = row.labels?.name ?? row.labels?.ap_name ?? 'Unknown'; grouped.set(name, [...(grouped.get(name) ?? []), row]); }); next[key] = [...grouped.entries()].map(([name, data], i) => ({ name, color: colors[i % colors.length], data: data.sort((a,b)=>(a.time ?? 0)-(b.time ?? 0)).map(p => ({ t: (p.time ?? 0) < 10000000000 ? (p.time ?? 0) * 1000 : (p.time ?? 0), v: p.value })) })); } setChartSeries(next); }).catch(() => undefined); }, [tr.earliest, tr.range, tr.refreshKey, tr.step]);
  useEffect(() => { void queryMetric('unpoller_client_uptime_seconds', undefined, tr.earliest).then(rows => { const channels = new Map<string, Set<string>>(); const vendors = new Map<string, Set<string>>(); rows.forEach(row => { const labels = row.labels ?? {}; const mac = labels.mac ?? labels.name ?? String(Math.random()); if (labels.channel) { const channel = labels.channel; if (!channels.has(channel)) channels.set(channel, new Set()); channels.get(channel)!.add(mac); } if (labels.channel) { const vendor = labels.oui ?? 'Unknown'; if (!vendors.has(vendor)) vendors.set(vendor, new Set()); vendors.get(vendor)!.add(mac); } }); setChannelItems([...channels.entries()].map(([label, macs]) => ({ label, value: macs.size })).sort((a,b) => b.value - a.value)); setVendorItems([...vendors.entries()].map(([label, macs]) => ({ label, value: macs.size })).sort((a,b) => b.value - a.value)); }).catch(() => undefined); }, [tr.earliest, tr.range, tr.refreshKey]);
  const percent = (v: number) => `${v.toFixed(1)}%`; const db = (v: number) => `${v.toFixed(0)} dB`;
  /* The AP list is built from device_info (no values); the per-AP numbers
     live in the chart series. Merge each series' latest point into the
     table rows — otherwise every column renders as an em dash. */
  const latest=(rows:LineSeries[]|undefined,name:string)=>rows?.find(s=>s.name===name)?.data.at(-1)?.v;
  /* Row tint by average client signal: ≥ -65 dBm good, ≥ -72 fair, below poor. */
  const tier=(v:number|undefined)=>v==null||!Number.isFinite(v)?'':v>=-65?'Good':v>=-72?'Fair':'Poor';
  const apRows=aps.map(a=>{const rv=latest(chartSeries.signal,a.name);return{...a,tier:tier(rv),clients:latest(chartSeries.clients,a.name)??NaN,two:latest(chartSeries.util24,a.name)??NaN,five:latest(chartSeries.util5,a.name)??NaN,cpu:latest(chartSeries.cpu,a.name)??NaN,memory:latest(chartSeries.memory,a.name)??NaN,rssi:Number.isFinite(rv)?db(rv as number):'—'};});
  return <div className={s.page}><header className={s.header}><h1>Access Points <small>UAP insights</small></h1><div className={s.controls}>{tr.rangeSelect}{tr.autoSelect}<button onClick={tr.refresh}>↻</button></div></header><div className={s.cards}>{[['Access points',count],['Wireless clients',clients],['2.4 GHz clients',two],['5 GHz clients',five]].map(([label,value])=><div className={s.card} key={String(label)}><span>{label}</span><strong>{value}</strong></div>)}</div><section className={s.inventory}><div className={s.panelTitle}><h2>Access points</h2><span>click an AP to see who's on it · avg client RSSI: ≥ -65 good · -65…-72 fair · &lt; -72 poor</span></div><table><thead><tr>{['Access point','Clients','2.4 GHz util','5 GHz util','CPU','Memory','Avg client RSSI'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{apRows.map(a=><tr key={a.name} className={a.tier?s[`row${a.tier}`]:undefined}><td><Link to={`/aps/${encodeURIComponent(a.name)}`}>{a.name}</Link></td><td>{Number.isFinite(a.clients) ? a.clients : '—'}</td><td>{Number.isFinite(a.two) ? percent(a.two) : '—'}</td><td>{Number.isFinite(a.five) ? percent(a.five) : '—'}</td><td>{Number.isFinite(a.cpu) ? percent(a.cpu) : '—'}</td><td>{Number.isFinite(a.memory) ? percent(a.memory) : '—'}</td><td className={a.tier?s[`rssi${a.tier}`]:undefined}>{a.rssi}</td></tr>)}{aps.length === 0 && <EmptyTableRows columns={7} rows={4}/>}</tbody></table></section><div className={s.grid}><Chart title="Clients per AP" format={v => v.toFixed(0)} yMax={16} series={chartSeries.clients}/><Chart title="Average client signal per AP" subtitle="mean client RSSI (dB) — higher is better" format={db} yMax={50} series={chartSeries.signal}/><Chart title="Wireless traffic per AP — transmit" format={v => `${v.toFixed(1)} MB/s`} area series={chartSeries.tx}/><Chart title="Wireless traffic per AP — receive" format={v => `${v.toFixed(0)} KB/s`} series={chartSeries.rx}/><Chart title="2.4 GHz channel utilization" format={percent} yMax={100} series={chartSeries.util24}/><Chart title="5 GHz channel utilization" format={percent} yMax={100} series={chartSeries.util5}/><Chart title="AP CPU usage" format={percent} yMax={100} series={chartSeries.cpu}/><Chart title="AP memory usage" format={percent} yMax={100} series={chartSeries.memory}/><Panel title="Clients by channel"><BarList items={channelItems} color="#347fce" /></Panel><Panel title="Clients by vendor (MAC OUI)"><BarList items={vendorItems} color="#347fce" /></Panel></div></div>;
}
