import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { apScoped, latestMetric, queryMetric, type MetricPoint } from '../api/metrics';
import { runQuery } from '../api/cribl';
import { investigatePrompt } from '../api/investigator';
import LineChart, { type LineSeries } from '../components/viz/LineChart';
import { useTimeRange } from '../components/TimeRange';
import s from './ApDetailPage.module.css';

const CLIENT_COLORS = ['#347fce','#238b3c','#d65b8d','#d69d2d','#3a9d84','#d86b3a','#4e5095','#d64f5c'];

const toSeries = (name:string,color:string,rows:MetricPoint[],format?:(v:number)=>string):LineSeries => ({name,color,data:rows.sort((a,b)=>(a.time??0)-(b.time??0)).map(p=>({t:(p.time??0)<1e10?(p.time??0)*1000:(p.time??0),v:p.value})),format});
const groupSeries = (rows:MetricPoint[],label:(r:MetricPoint)=>string,format?:(v:number)=>string,colors:string[]=CLIENT_COLORS):LineSeries[] => {const m=new Map<string,MetricPoint[]>();rows.forEach(r=>{const k=label(r);m.set(k,[...(m.get(k)??[]),r])});return [...m].sort((a,b)=>b[1].reduce((x,r)=>x+r.value,0)-a[1].reduce((x,r)=>x+r.value,0)).map(([name,rs],i)=>toSeries(name,colors[i%colors.length],rs,format))};
const latestPoint=(rows:MetricPoint[]):Map<string,MetricPoint>=>{const m=new Map<string,MetricPoint>();rows.forEach(p=>{const k=p.labels?.mac??p.labels?.name??'';if(k&&!m.has(k))m.set(k,p)});return m};
const rateFmt=(v:number)=>v>=1048576?`${(v/1048576).toFixed(1)} MB/s`:v>=1024?`${(v/1024).toFixed(1)} KB/s`:`${v.toFixed(0)} B/s`;
const bandName=(r:string)=>r==='ng'?'2.4 GHz':r==='axe'?'6 GHz':'5 GHz';

function EventsTable({ title, rows }: { title:string; rows:string[][] }) { return <section className={s.events}><div className={s.sectionHead}><h2>{title}</h2><span>connects, roams, disconnects from the controller log stream</span></div><table><thead><tr>{['Time','Event','Client','Detail'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j} className={j===1?'eventName':j===2?'link':''}>{v}</td>)}</tr>)}</tbody></table></section> }

export default function ApDetailPage() {
  const tr = useTimeRange();
 const {apName='AP Office'}=useParams(); const ap=decodeURIComponent(apName); const navigate=useNavigate(); const [kpi,setKpi]=useState({clients:0,rssi:0,cpu:0,memory:0,uptime:0}); const [liveEvents,setLiveEvents]=useState<string[][]>([]); const [rows,setRows]=useState<string[][]>([]);
 const [bands,setBands]=useState<LineSeries[]>([]); const [util,setUtil]=useState<LineSeries[]>([]); const [traffic,setTraffic]=useState<LineSeries[]>([]); const [signal,setSignal]=useState<LineSeries[]>([]); const [topDl,setTopDl]=useState<LineSeries[]>([]); const [retry,setRetry]=useState<LineSeries[]>([]); const [retryPct,setRetryPct]=useState<number | null>(null); const [health,setHealth]=useState<LineSeries[]>([]);
 useEffect(()=>{const q=(x:string,d:number)=>latestMetric(x,d); void runQuery(`dataset="main" | where _raw contains "CEF:0|Ubiquiti" | extend evt_name = extract(@"CEF:0\\|Ubiquiti\\|UniFi Network\\|[^|]*\\|\\d+\\|([^|]*)\\|", 1, _raw), client = extract(@"UNIFIclientHostname=(.*?) UNIFI[A-Za-z]", 1, _raw), ap_name = extract(@"UNIFIapFrom=(.*?) UNIFI[A-Za-z]", 1, _raw), cef_msg = extract(@" msg=(.*)$", 1, _raw) | where ap_name contains "${ap.replace(/"/g, '\\"')}" or cef_msg contains "${ap.replace(/"/g, '\\"')}" | project _time, evt_name, client, cef_msg | sort by _time desc | limit 100`, tr.earliest, 'now', 100).then(rows => { if (rows.length) setLiveEvents(rows.map(row => [new Date(Number(row._time) * 1000).toLocaleString('en-US', {month:'short', day:'numeric', hour:'2-digit', minute:'2-digit'}), String(row.evt_name ?? 'Event'), String(row.client ?? '—'), String(row.cef_msg ?? '—')])); }).catch(() => undefined); void Promise.all([q(`sum(${apScoped('unpoller_device_stations', `name="${ap}"`)})`,14),q(`avg(unpoller_client_rssi_db{ap_name="${ap}"})`,32),q(`100 * max(unpoller_device_cpu_utilization_ratio{name="${ap}"})`,12.5),q(`100 * max(unpoller_device_memory_utilization_ratio{name="${ap}"})`,70.7),q(`max(unpoller_device_uptime_seconds{name="${ap}"})`,kpi.uptime)]).then(([clients,rssi,cpu,memory,uptime])=>setKpi({clients,rssi,cpu,memory,uptime}));},[ap,kpi.uptime,tr.earliest,tr.range,tr.refreshKey]);
 useEffect(()=>{const esc=ap.replace(/"/g,'\\"');const scope=`ap_name="${esc}"`; void Promise.all([queryMetric(`unpoller_client_uptime_seconds{${scope}}`),queryMetric(`unpoller_client_rssi_db{${scope}}`),queryMetric(`unpoller_client_satisfaction_ratio{${scope}}`),queryMetric(`sum by (name, mac) (rate(unpoller_client_receive_bytes_total{${scope}}[5m]))`),queryMetric(`sum by (name, mac) (rate(unpoller_client_transmit_bytes_total{${scope}}[5m]))`)]).then(([up,rssi,sat,rx,tx])=>{const dur=(v:number)=>`${Math.floor(v/86400)}d ${Math.floor(v/3600)%24}h`;const byKey=latestPoint(up);const rssiM=latestPoint(rssi);const satM=latestPoint(sat);const rxM=latestPoint(rx);const txM=latestPoint(tx);setRows([...byKey.entries()].map(([key,p])=>{const l=p.labels??{};const rs=rssiM.get(key)?.value;const st=satM.get(key)?.value;return [String(l.name??key),String(l.ip??'—'),String(l.essid??'—'),String(l.radio_proto??(l.wired==='true'?'wired':'—')),String(l.channel??l.radio_chan??'—'),Number.isFinite(rs)?`${(rs as number).toFixed(0)} dB`:'—',rxM.has(key)?rateFmt(rxM.get(key)!.value):'—',txM.has(key)?rateFmt(txM.get(key)!.value):'—',Number.isFinite(st)?`${((st as number)*100).toFixed(1)}%`:'—',dur(p.value)];}));}).catch(()=>undefined);},[ap,tr.earliest,tr.range,tr.refreshKey]);
 useEffect(()=>{const esc=ap.replace(/"/g,'\\"');const scope=`ap_name="${esc}"`; void Promise.all([queryMetric(`sum by (radio) (unpoller_device_radio_stations{name="${esc}"})`,tr.step,tr.earliest),queryMetric(`100 * avg by (band) (unpoller_device_radio_channel_utilization_total_ratio{name="${esc}"})`,tr.step,tr.earliest),queryMetric(`sum by (name) (rate(unpoller_device_vap_receive_bytes_total{name="${esc}"}[5m]))`,tr.step,tr.earliest),queryMetric(`sum by (name) (rate(unpoller_device_vap_transmit_bytes_total{name="${esc}"}[5m]))`,tr.step,tr.earliest),queryMetric(`unpoller_client_rssi_db{${scope}}`,tr.step,tr.earliest),queryMetric(`topk(8, sum by (name) (rate(unpoller_client_receive_bytes_total{${scope}}[5m])))`,tr.step,tr.earliest),queryMetric(`100 * max(unpoller_device_cpu_utilization_ratio{name="${esc}"})`,tr.step,tr.earliest),queryMetric(`100 * max(unpoller_device_memory_utilization_ratio{name="${esc}"})`,tr.step,tr.earliest),queryMetric(`100 * unpoller_device_radio_transmit_retries{name="${esc}"} / (unpoller_device_radio_transmit_packets{name="${esc}"} > 0)`,tr.step,tr.earliest)]).then(([radioRows,utilRows,vapRx,vapTx,rssiRows,dlRows,cpuRows,memRows,retryRows])=>{setBands(groupSeries(radioRows,r=>bandName(r.labels?.radio??''),v=>v.toFixed(0),['#347fce','#238b3c','#d69d2d']));setUtil(groupSeries(utilRows,r=>`${r.labels?.band??'?'} GHz`,v=>`${v.toFixed(0)}%`,['#347fce','#238b3c','#d69d2d']));setTraffic([toSeries('Receive','#347fce',vapRx,v=>rateFmt(v)),toSeries('Transmit','#238b3c',vapTx,v=>rateFmt(v))]);setSignal(groupSeries(rssiRows,r=>r.labels?.name??'Client',v=>`${v.toFixed(0)} dB`).slice(0,8));setTopDl(groupSeries(dlRows,r=>r.labels?.name??'Client',v=>rateFmt(v)));setHealth([toSeries('CPU','#347fce',cpuRows,v=>`${v.toFixed(1)}%`),toSeries('Memory','#d65b8d',memRows,v=>`${v.toFixed(1)}%`)]);
/* Retry rate is our most actionable RF signal: retries are sparse but the
   ratios are stark (2.4 GHz runs ~20% vs ~0.2% on 6 GHz here), because
   unpoller exposes transmit_packets alongside retries. The `> 0` on the
   denominator drops radios that reported no packets instead of yielding NaN. */
setRetry(groupSeries(retryRows,r=>`${r.labels?.band??'?'} GHz`,v=>`${v.toFixed(1)}%`,['#347fce','#238b3c','#d69d2d']));
const byBand=new Map<string,{t:number;v:number}>();retryRows.forEach(p=>{const b=p.labels?.band??'?';const cur=byBand.get(b);if(!cur||(p.time??0)>=(cur.t))byBand.set(b,{t:p.time??0,v:p.value})});
const worst=[...byBand.values()].map(x=>x.v).filter(v=>Number.isFinite(v));setRetryPct(worst.length?Math.max(...worst):null);}).catch(()=>undefined);},[ap,tr.earliest,tr.range,tr.refreshKey,tr.step]);
 const fmtDuration=(v:number)=>`${Math.floor(v/86400)}d ${Math.floor(v/3600)%24}h`;
 return <div className={s.page}><div className={s.back} onClick={()=>navigate('/access-points')}>← All access points</div><header><div><h1>{ap} <small>Access point detail</small></h1></div><div className={s.actions}><button onClick={()=>navigate('/investigate',{state:{question:investigatePrompt.ap(ap)}})}>Investigate</button>{tr.rangeSelect}{tr.autoSelect}<button onClick={tr.refresh}>↻</button></div></header><div className={s.kpis}>{[['Clients',kpi.clients],['Avg client RSSI',`${kpi.rssi.toFixed(0)} dB`],['CPU',`${kpi.cpu.toFixed(1)}%`],['Memory',`${kpi.memory.toFixed(1)}%`],['Uptime',fmtDuration(kpi.uptime)],['Retry rate',retryPct===null?'—':`${retryPct.toFixed(1)}%`]].map(([l,v])=><div key={String(l)}><span>{l}</span><strong>{v}</strong></div>)}</div><section className={s.clientTable}><div className={s.sectionHead}><h2>Connected clients</h2><span>{kpi.clients} on this AP now — click a client to drill in</span></div><table><thead><tr>{['Client','IP','Network','Proto','Channel','RSSI','Download','Upload','Satisfaction','Uptime'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j} className={j===0?'link':''}>{j===0?<Link to={`/clients/${encodeURIComponent(r[0])}`}>{v}</Link>:v}</td>)}</tr>)}{rows.length===0&&<tr><td colSpan={10}>No wireless clients on this AP in this time range</td></tr>}</tbody></table></section><div className={s.grid}><LineChart title="Clients by band" subtitle="station count per radio band" series={bands} height={205} yMax={10}/><LineChart title="Channel utilization by band" subtitle="avg radio channel utilization" series={util} height={205} yMax={100}/><LineChart title="Radio retry rate" subtitle="retries ÷ transmit packets, by band — a high 2.4 GHz line is congestion, not a fault" series={retry} height={205} yFormat={x=>`${x.toFixed(1)}%`}/><LineChart title="Wireless traffic" subtitle="VAP bytes/s on this AP" series={traffic} height={205} area/><LineChart title="Client signal on this AP" subtitle="per-client RSSI (dB) — click a line for that client" series={signal} height={205} yMax={60}/><LineChart title="Top clients by download" subtitle="topk(8), rate over 5m — click a line for that client" series={topDl} height={205}/><LineChart title="AP health" subtitle="device CPU and memory utilization" series={health} height={205} yMax={100}/></div><EventsTable title="Events involving this AP · time range" rows={liveEvents}/></div>;
}
