import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { gatewayScoped, latestMetric, queryMetric, type MetricPoint } from '../api/metrics';
import LineChart, { type LineSeries } from '../components/viz/LineChart';
import { investigatePrompt } from '../api/investigator';
import { useTimeRange } from '../components/TimeRange';
import s from './GatewayPage.module.css';
const colors=['#347fce','#238b3c','#d36b96'];
const grouped=(rows:MetricPoint[], label:(r:MetricPoint)=>string, format?:(v:number)=>string):LineSeries[]=>{const m=new Map<string,MetricPoint[]>();rows.forEach(r=>{const k=label(r);m.set(k,[...(m.get(k)??[]),r])});return [...m].map(([name,rs],i)=>({name,color:colors[i%3],data:rs.sort((a,b)=>(a.time??0)-(b.time??0)).map(r=>({t:(r.time??0)<1e10?(r.time??0)*1000:r.time!,v:r.value})),format}))};
export default function GatewayPage(){const navigate=useNavigate();const tr=useTimeRange(); const [v,setV]=useState({uptime:0,cpu:0,memory:0,speed:0,latency:0,clients:0});const [isp,setIsp]=useState({down:0,up:0,latency:0,lastTest:0});const [charts,setCharts]=useState<Record<string,LineSeries[]>>({});
/* A single named series — used for the ISP panels, which aggregate across WAN
   groups so the idle second WAN (all zeros) cannot draw a false "outage" line. */
const one=(name:string,color:string,rows:MetricPoint[],format:(v:number)=>string):LineSeries=>({name,color,data:rows.sort((a,b)=>(a.time??0)-(b.time??0)).map(r=>({t:(r.time??0)<1e10?(r.time??0)*1000:r.time!,v:r.value})),format});useEffect(()=>{const q=(x:string,d:number)=>latestMetric(x,d);void Promise.all([q(`${gatewayScoped('unpoller_device_uptime_seconds')}`,v.uptime),q(`100 * max(${gatewayScoped('unpoller_device_cpu_utilization_ratio')})`,85),q(`100 * max(${gatewayScoped('unpoller_device_memory_utilization_ratio')})`,64.3),q('max(unpoller_device_wan_speed_bps)',1e9),q('1000 * avg(unpoller_site_latency_seconds)',11),q(`sum(${gatewayScoped('unpoller_device_stations')})`,75),q('max(unpoller_speedtest_download_mbps)',0),q('max(unpoller_speedtest_upload_mbps)',0),q('max(unpoller_speedtest_latency_ms)',0),q('max(unpoller_speedtest_timestamp_seconds)',0)]).then(([uptime,cpu,memory,speed,latency,clients,ispDown,ispUp,ispLat,ispTs])=>{setV({uptime,cpu,memory,speed,latency,clients});setIsp({down:ispDown,up:ispUp,latency:ispLat,lastTest:ispTs})});void Promise.all([queryMetric('sum(rate(unpoller_device_wan_receive_bytes_total[5m]))',tr.step,tr.earliest),queryMetric('sum(rate(unpoller_device_wan_transmit_bytes_total[5m]))',tr.step,tr.earliest),queryMetric('sum(rate(unpoller_device_lan_receive_bytes_total[5m]))',tr.step,tr.earliest),queryMetric('sum(rate(unpoller_device_lan_transmit_bytes_total[5m]))',tr.step,tr.earliest),queryMetric('sum(rate(unpoller_device_wan_receive_packets_total[5m]))',tr.step,tr.earliest),queryMetric('sum(rate(unpoller_device_wan_transmit_packets_total[5m]))',tr.step,tr.earliest),queryMetric(`max(${gatewayScoped('unpoller_device_load_average_1')})`,tr.step,tr.earliest),queryMetric(`max(${gatewayScoped('unpoller_device_load_average_5')})`,tr.step,tr.earliest),queryMetric(`max(${gatewayScoped('unpoller_device_load_average_15')})`,tr.step,tr.earliest),queryMetric('sum(rate(unpoller_device_wan_receive_dropped_total[5m]))',tr.step,tr.earliest),queryMetric('sum(rate(unpoller_device_wan_transmit_dropped_total[5m]))',tr.step,tr.earliest),queryMetric(`avg by (temp_type, tag) (${gatewayScoped('unpoller_device_temperature_celsius')})`,tr.step,tr.earliest)]).then(([wr,wt,lr,lt,pr,pt,l1,l5,l15,dr,dt,temp])=>{const f=(x:number)=>`${(x/1024/1024).toFixed(1)} MB/s`;setCharts({wan:[...grouped(wr,()=> 'Receive',f),...grouped(wt,()=> 'Transmit',f)],lan:[...grouped(lr,()=> 'Receive',f),...grouped(lt,()=> 'Transmit',f)],packets:[...grouped(pr,()=> 'Receive',x=>`${x.toFixed(0)} packets/s`),...grouped(pt,()=> 'Transmit',x=>`${x.toFixed(0)} packets/s`)],load:[...grouped(l1,()=> '1m',x=>x.toFixed(1)),...grouped(l5,()=> '5m',x=>x.toFixed(1)),...grouped(l15,()=> '15m',x=>x.toFixed(1))],drops:[...grouped(dr,()=> 'Receive',x=>x.toFixed(2)),...grouped(dt,()=> 'Transmit',x=>x.toFixed(2))],temp:grouped(temp,r=>r.labels?.tag??r.labels?.temp_type??'Temperature',x=>`${x.toFixed(1)}°C`)});}).catch(()=>undefined)},[tr.earliest,tr.range,tr.refreshKey,tr.step,v.uptime]);
/* Speed tests are sparse (roughly hourly at best), so they get their own fixed
   7-day window rather than the page time range — a 1h view would look empty.
   max() across WAN groups picks the active link: the idle second WAN reports 0. */
useEffect(()=>{void Promise.all([queryMetric('max(unpoller_speedtest_download_mbps)',21600,'-7d'),queryMetric('max(unpoller_speedtest_upload_mbps)',21600,'-7d'),queryMetric('max(unpoller_speedtest_latency_ms)',21600,'-7d')]).then(([d,u,l])=>setCharts(c=>({...c,speed:[one('Download',colors[0],d,v=>`${v.toFixed(0)} Mbps`),one('Upload',colors[1],u,v=>`${v.toFixed(0)} Mbps`)],speedLat:[one('Latency',colors[0],l,v=>`${v.toFixed(0)} ms`)]}))).catch(()=>undefined)},[tr.refreshKey]);const uptime=`${Math.floor(v.uptime/86400)}d ${Math.floor(v.uptime/3600)%24}h`;const lastTest=(()=>{if(!isp.lastTest)return '—';const age=Math.max(0,Math.round(Date.now()/1000-isp.lastTest));return age<3600?`${Math.round(age/60)}m ago`:age<86400?`${Math.round(age/3600)}h ago`:`${Math.round(age/86400)}d ago`})();const fmt=(key:string)=>charts[key] ?? [];return <div className={s.page}><header><h1>Gateway <small>UDM insights</small></h1><div className={s.actions}><button onClick={()=>navigate('/investigate',{state:{question:investigatePrompt.gateway()}})}>Investigate</button>{tr.rangeSelect}{tr.autoSelect}<button onClick={tr.refresh}>↻</button></div></header><div className={s.cards}>{[['Uptime',uptime],['CPU',`${v.cpu.toFixed(1)}%`],['Memory',`${v.memory.toFixed(1)}%`],['WAN link speed',`${(v.speed/1e9).toFixed(1)} Gbps`],['WAN latency',`${v.latency.toFixed(1)} ms`],['Directly connected',v.clients],['ISP download',`${isp.down.toFixed(0)} Mbps`],['ISP upload',`${isp.up.toFixed(0)} Mbps`],['Speed test latency',`${isp.latency.toFixed(0)} ms`],['Last speed test',lastTest]].map(([l,x])=><div className={s.card} key={String(l)}><span>{l}</span><strong>{x}</strong></div>)}</div><div className={s.grid}><LineChart title="WAN throughput" series={fmt('wan')} height={220} area yFormat={x=>`${(x/1024/1024).toFixed(1)} MB/s`}/><LineChart title="LAN throughput" series={fmt('lan')} height={220} area yFormat={x=>`${(x/1024/1024).toFixed(1)} MB/s`}/><LineChart title="WAN packets" subtitle="packets/s" series={fmt('packets')} height={220}/><LineChart title="Load average" series={fmt('load')} height={220}/><LineChart title="WAN drops" subtitle="dropped packets/s" series={fmt('drops')} height={220} yMax={1}/><LineChart title="ISP speed tests" subtitle="controller speed tests, last 7 days — the ISP truth, not the Wi-Fi" series={fmt('speed')} height={220} area yFormat={x=>`${x.toFixed(0)} Mbps`}/><LineChart title="Speed test latency" subtitle="ping during the controller's speed test, last 7 days" series={fmt('speedLat')} height={220} yFormat={x=>`${x.toFixed(0)} ms`}/><LineChart title="Gateway temperatures" series={fmt('temp')} height={220} yMax={60} yFormat={x=>`${x.toFixed(1)}°C`}/></div></div>}
