import { useEffect, useState, type ReactNode } from 'react';
import { latestMetric, queryMetric, type MetricPoint } from '../api/metrics';
import LineChart, { type LineSeries } from '../components/viz/LineChart';
import { useTimeRange } from '../components/TimeRange';
import s from './OverviewPage.module.css';

type Device = { name: string; type: string; model: string; ip: string; version: string; clients: number; cpu: number; memory: number; uptime: string };

const devices: Device[] = [
  ['AP Bedroom 2','UAP','U6M','10.10.8.15','6.8.2.15592',2,6,68.4,'113d 0h'], ['AP Guest House','UAP','U6M','10.10.8.13','6.8.2.15592',0,7,71.4,'112d 6h'], ['AP Guest House Patio','UAP','UKPW','10.10.8.17','8.6.11.18870',1,1.3,78.6,'78d 13h'], ['AP Laundry South','UAP','U6M','10.10.8.16','6.8.2.15592',6,6.4,69.5,'114d 1h'], ['AP Main Bedroom','UAP','U6M','10.10.8.11','6.8.2.15592',2,8.1,68.3,'114d 3h'], ['AP Office','UAP','U6M','10.10.8.14','6.8.2.15592',15,11.6,71.1,'113d 0h'], ['AP Theater Rack','UAP','U6M','10.10.8.12','6.8.2.15592',2,7.7,67.8,'113d 0h'], ['Sharp - Los Gatos','UDM','UDMPROSE','71.198.192.159','5.1.15.33416',75,91.4,69.4,'84d 13h'], ['1 Switch Theater Rack PoE','USW','USPM48P','10.10.8.3','7.5.10.17129',22,11.6,15.7,'10d 13h'], ['2 Switch Main Bedroom','USW','USWED37','10.10.8.6','2.1.8.971',1,11.5,86.1,'114d 3h'], ['2 Switch Mechanical Room','USW','USPM24P','10.10.8.5','7.5.10.17129',16,15.4,14,'10d 13h'], ['2 Switch Theater Rack','USW','USPM48','10.10.8.4','7.5.10.17129',11,10.6,15.7,'10d 13h'], ['3 Switch Guest House','USW','USWED37','10.10.8.7','2.1.8.971',0,11.2,86.2,'115d 6h'],
].map(([name,type,model,ip,version,clients,cpu,memory,uptime]) => ({ name, type, model, ip, version, clients, cpu, memory, uptime } as Device));

const sample = (): MetricPoint[] => [];
const chartSeries = (name: string, color: string, points: MetricPoint[], format?: (v: number) => string): LineSeries => ({ name, color, data: points.map((p, i) => ({ t: (p.time ?? Date.now() - (points.length - i) * 120000) * (p.time && p.time < 10000000000 ? 1000 : 1), v: p.value })), format });

function Panel({ title, subtitle, children, className = '' }: { title: string; subtitle?: string; children: ReactNode; className?: string }) { return <section className={`${s.panel} ${className}`}><div className={s.panelHead}><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div></div>{children}</section>; }

export default function OverviewPage() {
  const [values, setValues] = useState({ aps: 7, switches: 6, gateways: 1, users: 79, guests: 0, iots: 1, latency: 18, uptime: 1296000 });
  const [receive, setReceive] = useState<MetricPoint[]>([]); const [transmit, setTransmit] = useState<MetricPoint[]>([]); const [userSeries, setUserSeries] = useState<MetricPoint[]>([]);
  const tr = useTimeRange();
  useEffect(() => { void Promise.all([latestMetric('sum(unpoller_site_aps)',7),latestMetric('sum(unpoller_site_switches)',6),latestMetric('sum(unpoller_site_gateways)',1),latestMetric('sum(unpoller_site_users)',79),latestMetric('sum(unpoller_site_guests)',0),latestMetric('sum(unpoller_site_iots)',1),latestMetric('1000 * avg(unpoller_site_latency_seconds)',18),latestMetric('max(unpoller_site_uptime_seconds)',1296000)]).then(([aps,switches,gateways,users,guests,iots,latency,uptime]) => setValues({ aps,switches,gateways,users,guests,iots,latency,uptime })); void Promise.all([queryMetric('sum(unpoller_site_receive_rate_bytes)',tr.step,tr.earliest),queryMetric('sum(unpoller_site_transmit_rate_bytes)',tr.step,tr.earliest),queryMetric('sum(unpoller_site_users)',tr.step,tr.earliest)]).then(([r,t,u]) => { if(r.length) setReceive(r); if(t.length) setTransmit(t); if(u.length) setUserSeries(u); }); }, [tr.earliest, tr.range, tr.refreshKey, tr.step]);
  const cards = [['Access points', values.aps, ''], ['Switches', values.switches, ''], ['Gateways', values.gateways, ''], ['Clients', values.users, ''], ['Guests', values.guests, ''], ['IoT devices', values.iots, ''], ['WAN latency', `${values.latency.toFixed(1)} ms`, 'blue'], ['Uplink uptime', `${Math.floor(values.uptime / 86400)}d ${Math.floor(values.uptime / 3600) % 24}h`, '']];
  const eventRows = [['WiFi Client Roamed',25],['Device syslog — warning',6],['Device syslog — error',5],['WiFi Client Connected',1]];
  const receiveSeries = chartSeries('Receive', '#347fce', receive, v => `${(v / 1024 / 1024).toFixed(1)} MB/s`);
  const transmitSeries = chartSeries('Transmit', '#238b3c', transmit, v => `${(v / 1024 / 1024).toFixed(1)} MB/s`);
  const users = chartSeries('Users', '#347fce', userSeries, v => v.toFixed(0));
  const guests = chartSeries('Guests', '#238b3c', sample(), v => v.toFixed(0));
  const iots = chartSeries('IoT', '#d65b8d', sample(), v => v.toFixed(0));
  return <div className={s.page}><header className={s.header}><div><h1>Network Overview <small>UniFi via UnPoller</small></h1></div><div className={s.controls}>{tr.rangeSelect}{tr.autoSelect}<button aria-label="Refresh" onClick={tr.refresh}>↻</button></div></header><div className={s.cards}>{cards.map(([label,value,kind]) => <div className={s.card} key={String(label)}><span>{label}</span><strong className={kind === 'blue' ? s.blue : ''}>{value}</strong></div>)}</div><div className={s.grid}><LineChart title="Site throughput" subtitle="unpoller_site_*_rate_bytes" series={[receiveSeries, transmitSeries]} height={190} area/><LineChart title="Connected clients" subtitle="users / guests / IoT" series={[users, guests, iots]} height={190} yMax={100}/><LineChart title="Internet drops" subtitle="rate(unpoller_site_intenet_drops_total[5m])" series={[chartSeries('Drops', '#347fce', sample())]} height={190} yMax={1}/><Panel title="Network events" subtitle="from the UniFi log streams, over the selected window"><div className={s.events}>{eventRows.map(([name,count]) => <div key={String(name)}><span>{name}</span><b style={{width:`${Number(count)/25*82}%`}}/><em>{count}</em></div>)}<a>View all events →</a></div></Panel></div><Panel title="Device inventory" subtitle={`${devices.length} devices — APs and switches drill through`}><div className={s.tableWrap}><table><thead><tr>{['Device','Type','Model','IP','Version','Clients','CPU','Memory','Uptime'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{devices.map(d=><tr key={d.name}><td><a>{d.name}</a></td><td>{d.type}</td><td>{d.model}</td><td>{d.ip}</td><td>{d.version}</td><td>{d.clients}</td><td>{d.cpu.toFixed(1)}%</td><td>{d.memory.toFixed(1)}%</td><td>{d.uptime}</td></tr>)}</tbody></table></div></Panel></div>;
}
